### ISSUE TITLE
Can't localize / change BP Group tab name

### ISSUE THREAD

**Issue by schwarzaufweiss** [imath/rendez-vous#21]
Hi imath,
I have localized Rendez-vous 1.1.0 and change for internal use "Rendez-vous" to "Doodle". Everything works fine except for the BP group tab and subnav in group admin incl settings strings. All these are still saying "Rendez-vous". What's the place you define "Rendez-vous" for that use?

**Comment by imath** [comment]
this will be fixed by patch attached to #22
