### ISSUE TITLE
time rejected in firefox and IE

### ISSUE THREAD

**Issue by LYPratt** [imath/rendez-vous#42]
Hi there, what a great plugin!  Unfortunately, I can't enter a time in either firefox or in IE ( I don't use Chrome).  I type 21:00, 22:00, 23:00 (which all fit your regex, strange!) but receive the message: "Please make sure to respect the format HH:MM when defining time."  I think that you need to null out the error instead of making it an array before doing the time parse?  Just a guess.  See this screenshot
![capture](https://cloud.githubusercontent.com/assets/7600067/12083941/65737982-b269-11e5-8bea-929ea8f016b8.PNG)

**Comment by imath** [comment]
Just tested in FF, everything works fine as long as all time inputs are formated this way (including the duration field in first tab)
